apiVersion: apps/v1
kind: Deployment
metadata:
  name: alumno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alumno
  template:
    metadata:
      labels:
        app: alumno
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: alumno
        image: carlodelgado/huawei-alumno:latest
        env:
        - name: FOO
          value: "bar"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 7000
          name: alumno
---
apiVersion: v1
kind: Service
metadata:
  name: alumno
spec:
  type: LoadBalancer
  ports:
  - port: 7000
  selector:
    app: alumno